/* ==========================================================================
   AdsorpFit: built-in example datasets.

   Generated by tools/make_presets.py from validation/datasets/. Every entry
   is real measured data from an open-access paper with an openly licensed
   dataset, not a synthetic curve, and each carries its citation. The set is
   chosen to span behaviours rather than to flatter the tool: two clean
   saturating isotherms, one that never plateaus, one failing adsorbent with
   negative uptake, and four kinetic runs ranging from a clean approach to
   equilibrium to one that finishes before the first measurement.
   ========================================================================== */

const PRESETS = [
  {
    "id": "wang_mg_iso",
    "cat": "isotherm",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Raw data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Mg-biochar (isotherm)",
      "note": "Ten equilibrium points with replicate standard deviations, reaching a clear plateau. The authors' best performer. Langmuir gives 106.3 mg/g, Sips 112.5 mg/g."
    },
    "ko": {
      "name": "Mg-바이오차의 인산염 흡착 (등온)",
      "note": "반복 측정 표준편차를 포함한 평형 데이터 10점이며 뚜렷한 평형값에 도달합니다. 논문에서 가장 성능이 좋은 흡착제로, Langmuir는 106.3 mg/g, Sips는 112.5 mg/g를 보고했습니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tsd\tC0 (mg/L)\n16.2\t41.1\t0\t100\n67.2\t66.6\t0.2\t200\n125.7\t81.3\t3.4\t300\n200.7\t90.5\t1.4\t400\n304.6\t96.2\t2.4\t500\n412.8\t98.6\t3.6\t600\n608.9\t101.6\t0.6\t800\n789.3\t102.8\t3\t1000\n984.4\t103.4\t2.4\t1200\n1304\t104.6\t3.6\t1500",
    "ctx": {
      "T": "298.15",
      "MW": "94.97",
      "Cs": "",
      "dose": "2"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "wang_ca_iso",
    "cat": "isotherm",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Raw data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Ca-biochar (isotherm)",
      "note": "A case where the three-parameter Sips clearly beats Langmuir: the authors report R2 rising from 0.947 to 0.992, and q_max falling from 91.6 to 81.5 mg/g."
    },
    "ko": {
      "name": "Ca-바이오차의 인산염 흡착 (등온)",
      "note": "3-매개변수 Sips가 Langmuir보다 뚜렷하게 우수한 사례입니다. 논문에서 R2가 0.947에서 0.992로 오르고 q_max는 91.6에서 81.5 mg/g로 내려갑니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tsd\tC0 (mg/L)\n54.7\t21.8\t2.4\t100\n116.3\t39.6\t2.5\t200\n182.8\t57.2\t2.4\t300\n254.4\t67.1\t6.2\t400\n357.3\t72.4\t2.2\t500\n428.7\t75.4\t0.3\t600\n640.4\t77.3\t0.6\t800\n810.3\t78.2\t1.2\t1000\n1019\t78.9\t1.9\t1200\n1302\t79.5\t0.1\t1500",
    "ctx": {
      "T": "298.15",
      "MW": "94.97",
      "Cs": "",
      "dose": "2"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "hill"
    ]
  },
  {
    "id": "wang_al_iso",
    "cat": "isotherm",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Raw data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Al-biochar (no plateau)",
      "note": "Still climbing at the highest concentration, so any q_max is an extrapolation. Use it to see the no-plateau warning and how far Langmuir and Sips disagree when saturation is not reached."
    },
    "ko": {
      "name": "Al-바이오차의 인산염 흡착 (평형 미도달)",
      "note": "최고 농도에서도 계속 증가하므로 q_max는 외삽값입니다. 평형 미도달 경고와, 포화에 이르지 못했을 때 Langmuir와 Sips가 얼마나 어긋나는지 확인해 보세요."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tsd\tC0 (mg/L)\n67.7\t15.2\t0.1\t100\n144.5\t25.4\t1\t200\n226\t35.6\t1.9\t300\n306.9\t40.9\t1.3\t400\n410.4\t45.8\t2.3\t500\n475.2\t52.1\t2.4\t600\n670.3\t62.4\t1.2\t800\n827.3\t69.7\t0.1\t1000\n1022\t77.4\t0.4\t1200\n1292\t84.8\t1.8\t1500",
    "ctx": {
      "T": "298.15",
      "MW": "94.97",
      "Cs": "",
      "dose": "2"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth"
    ]
  },
  {
    "id": "wang_bc_iso",
    "cat": "isotherm",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Raw data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on plain biochar (a failing adsorbent)",
      "note": "The unmodified control, which adsorbs almost nothing and records a negative uptake at the lowest concentration. Every diagnostic should object; this is what a bad dataset looks like."
    },
    "ko": {
      "name": "무처리 바이오차 (흡착이 되지 않는 경우)",
      "note": "개질하지 않은 대조군으로 거의 흡착되지 않으며 최저 농도에서는 음의 흡착량이 기록됩니다. 모든 진단이 경고를 내야 하며, 잘못된 데이터가 어떤 모습인지 보여 줍니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tsd\tC0 (mg/L)\n97.8\t-1.2\t0.5\t100\n189.6\t0.1\t0.8\t200\n282.5\t2.9\t0.5\t300\n371.9\t3.2\t0\t400\n492.2\t3.6\t1.2\t500\n556\t4.5\t3\t600\n765.3\t7.7\t0.6\t800\n924.3\t8.4\t1.2\t1000\n1124\t9.6\t0\t1200\n1396\t10.8\t1.2\t1500",
    "ctx": {
      "T": "298.15",
      "MW": "94.97",
      "Cs": "",
      "dose": "2"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips"
    ]
  },
  {
    "id": "wang_ca_kin",
    "cat": "kinetics",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Raw data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Ca-biochar (kinetics)",
      "note": "Twelve time points over 72 h that reach a clean plateau. The authors report PFO q_e = 9.35 and PSO q_e = 9.84 mg/g."
    },
    "ko": {
      "name": "Ca-바이오차의 인산염 흡착 (동역학)",
      "note": "72시간에 걸친 12개 시점으로 평형에 깨끗하게 도달합니다. 논문의 PFO q_e는 9.35, PSO q_e는 9.84 mg/g입니다."
    },
    "data": "t (h)\tqt (mg/g)\tsd\n0.5\t6.83\t0.29\n1\t7.1\t0.08\n1.5\t7.23\t0.15\n2\t7.75\t0.12\n3\t8.84\t0.21\n4\t9.31\t0.04\n6\t9.56\t0.04\n8\t9.62\t0.06\n12\t9.76\t0.05\n24\t9.79\t0.06\n48\t9.82\t0.01\n72\t9.83\t0.01",
    "ctx": {
      "T": "298.15",
      "C0": "20",
      "dose": "2",
      "radius": "0.05"
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami",
      "weber_morris"
    ]
  },
  {
    "id": "wang_al_kin",
    "cat": "kinetics",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Raw data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Al-biochar (never equilibrates)",
      "note": "Uptake is still rising after 72 h, which the authors note explicitly. Any fitted q_e extrapolates beyond the measurement, and AdsorpFit says so."
    },
    "ko": {
      "name": "Al-바이오차 (평형에 도달하지 않음)",
      "note": "72시간 후에도 흡착량이 계속 증가하며, 논문에서도 이를 명시하고 있습니다. 피팅된 q_e는 측정 범위를 벗어난 외삽값이며 AdsorpFit이 이를 알려 줍니다."
    },
    "data": "t (h)\tqt (mg/g)\tsd\n0.5\t1.81\t0.3\n1\t2.34\t0.43\n1.5\t2.52\t0.36\n2\t2.86\t0.22\n3\t2.88\t0.14\n4\t3.45\t0.15\n6\t3.78\t0.2\n8\t4.05\t0.24\n12\t5.23\t0.47\n24\t6.55\t0.37\n48\t8.34\t0.48\n72\t9.25\t0.01",
    "ctx": {
      "T": "298.15",
      "C0": "20",
      "dose": "2",
      "radius": "0.05"
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami",
      "weber_morris"
    ]
  },
  {
    "id": "wang_mg_kin",
    "cat": "kinetics",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Raw data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Mg-biochar (two-stage uptake)",
      "note": "A slow start then a sharp rise between 1.5 and 2 h, giving a clear two-stage shape. Good for the Weber-Morris multi-region analysis and the double-exponential model."
    },
    "ko": {
      "name": "Mg-바이오차 (2단계 흡착)",
      "note": "초기에는 느리다가 1.5~2시간 사이에 급격히 증가하는 뚜렷한 2단계 형태입니다. Weber–Morris 다구간 해석과 이중지수 모델을 시험하기에 좋습니다."
    },
    "data": "t (h)\tqt (mg/g)\tsd\n0.5\t1.51\t0.02\n1\t1.98\t0.04\n1.5\t2.63\t0.03\n2\t7.38\t0.01\n3\t8.53\t0.03\n4\t8.93\t0.04\n6\t9.28\t0\n8\t9.54\t0.03\n12\t9.56\t0.02\n24\t9.86\t0.02\n48\t9.73\t0.01\n72\t9.82\t0.01",
    "ctx": {
      "T": "298.15",
      "C0": "20",
      "dose": "2",
      "radius": "0.05"
    },
    "models": [
      "pfo",
      "pso",
      "double_exponential",
      "avrami",
      "weber_morris"
    ]
  },
  {
    "id": "wang_la_kin",
    "cat": "kinetics",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Raw data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on La-biochar (equilibrium before the first point)",
      "note": "Adsorption is complete within the first half hour, so the whole curve is flat and the rate constant is undetermined. Shows why early sampling matters more than run length."
    },
    "ko": {
      "name": "La-바이오차 (첫 측정 이전에 평형 도달)",
      "note": "첫 30분 안에 흡착이 끝나 곡선 전체가 평평하고 속도상수를 구할 수 없습니다. 실험 시간보다 초기 구간의 샘플링이 왜 더 중요한지 보여 줍니다."
    },
    "data": "t (h)\tqt (mg/g)\tsd\n0.5\t9.82\t0.04\n1\t9.87\t0.02\n1.5\t9.88\t0.03\n2\t9.87\t0.02\n3\t9.87\t0.02\n4\t9.88\t0.02\n6\t9.91\t0.01\n8\t9.89\t0.02\n12\t9.88\t0.04\n24\t9.91\t0.01\n48\t9.9\t0.01\n72\t9.91\t0.02",
    "ctx": {
      "T": "298.15",
      "C0": "20",
      "dose": "2",
      "radius": "0.05"
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  }
];
