/* ==========================================================================
   AdsorpFit: built-in example datasets.

   Generated by tools/make_presets.py from validation/datasets/. Every entry
   is real measured data from an open-access paper whose authors deposited
   the raw numbers under an open licence, not a synthetic curve and not a
   figure read off with a ruler, and each carries its citation.

   The set is chosen to span behaviours rather than to flatter the tool:
   isotherms that saturate and isotherms that never do, an adsorbent that
   fails outright and records negative uptake, kinetic runs that finish
   before the first measurement and others still climbing at the end, a
   capacity the source paper obtained from a linearised plot that the
   non-linear fit does not support, and a tabulated rate constant that its
   own deposited data contradict.

   Five contaminants across nine adsorbents: phosphate, arsenic, fluoride,
   cadmium and an antibiotic.
   ========================================================================== */

const PRESETS = [
  {
    "id": "wang_mg_iso",
    "cat": "isotherm",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Mg-biochar (isotherm)",
      "note": "Ten equilibrium points with replicate standard deviations, reaching a clear plateau. The authors' best performer. Langmuir gives 106.3 mg/g, Sips 112.5 mg/g."
    },
    "ko": {
      "name": "Mg-바이오차의 인산염 흡착 (등온)",
      "note": "반복 측정 표준편차를 포함한 평형 데이터 10점이며 뚜렷한 평형값에 도달합니다. 논문에서 가장 성능이 좋은 흡착제로, Langmuir는 106.3 mg/g, Sips는 112.5 mg/g를 보고했습니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tsd\tC0 (mg/L)\n16.2\t41.1\t0\t100\n67.2\t66.6\t0.2\t200\n125.7\t81.3\t3.4\t300\n200.7\t90.5\t1.4\t400\n304.6\t96.2\t2.4\t500\n412.8\t98.6\t3.6\t600\n608.9\t101.6\t0.6\t800\n789.3\t102.8\t3\t1000\n984.4\t103.4\t2.4\t1200\n1304\t104.6\t3.6\t1500",
    "ctx": {
      "T": "298.15",
      "MW": "94.97",
      "Cs": "",
      "dose": "2"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "wang_ca_iso",
    "cat": "isotherm",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Ca-biochar (isotherm)",
      "note": "A textbook saturating isotherm: the top third of the concentration range adds almost nothing, so the fitted capacity is measured rather than extrapolated."
    },
    "ko": {
      "name": "Ca-바이오차의 인산염 흡착 (등온)",
      "note": "교과서적인 포화형 등온선입니다. 농도 범위의 상위 3분의 1에서 흡착량이 거의 늘지 않으므로, 적합된 흡착용량은 외삽이 아니라 측정된 값입니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tsd\tC0 (mg/L)\n54.7\t21.8\t2.4\t100\n116.3\t39.6\t2.5\t200\n182.8\t57.2\t2.4\t300\n254.4\t67.1\t6.2\t400\n357.3\t72.4\t2.2\t500\n428.7\t75.4\t0.3\t600\n640.4\t77.3\t0.6\t800\n810.3\t78.2\t1.2\t1000\n1019\t78.9\t1.9\t1200\n1302\t79.5\t0.1\t1500",
    "ctx": {
      "T": "298.15",
      "MW": "94.97",
      "Cs": "",
      "dose": "2"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "wang_al_iso",
    "cat": "isotherm",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Al-biochar (no plateau)",
      "note": "Still rising at the highest concentration. Every saturation model will report a q_max here, and every one of them is an extrapolation. AdsorpFit says so."
    },
    "ko": {
      "name": "Al-바이오차의 인산염 흡착 (평탄역 없음)",
      "note": "가장 높은 농도에서도 계속 상승합니다. 모든 포화 모델이 q_max를 보고하지만 그 값은 모두 외삽이며, AdsorpFit은 이를 경고합니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tsd\tC0 (mg/L)\n67.7\t15.2\t0.1\t100\n144.5\t25.4\t1\t200\n226\t35.6\t1.9\t300\n306.9\t40.9\t1.3\t400\n410.4\t45.8\t2.3\t500\n475.2\t52.1\t2.4\t600\n670.3\t62.4\t1.2\t800\n827.3\t69.7\t0.1\t1000\n1022\t77.4\t0.4\t1200\n1292\t84.8\t1.8\t1500",
    "ctx": {
      "T": "298.15",
      "MW": "94.97",
      "Cs": "",
      "dose": "2"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "wang_bc_iso",
    "cat": "isotherm",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on plain biochar (a failing adsorbent)",
      "note": "The unmodified biochar adsorbs almost nothing and one measured loading is negative. Kept deliberately: it is the case every diagnostic should object to."
    },
    "ko": {
      "name": "무처리 바이오차의 인산염 흡착 (실패한 흡착제)",
      "note": "개질하지 않은 바이오차는 거의 흡착하지 않으며 측정된 흡착량 하나는 음수입니다. 모든 진단 기능이 문제를 제기해야 하는 사례로 일부러 포함했습니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tsd\tC0 (mg/L)\n97.8\t-1.2\t0.5\t100\n189.6\t0.1\t0.8\t200\n282.5\t2.9\t0.5\t300\n371.9\t3.2\t0\t400\n492.2\t3.6\t1.2\t500\n556\t4.5\t3\t600\n765.3\t7.7\t0.6\t800\n924.3\t8.4\t1.2\t1000\n1124\t9.6\t0\t1200\n1396\t10.8\t1.2\t1500",
    "ctx": {
      "T": "298.15",
      "MW": "94.97",
      "Cs": "",
      "dose": "2"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "wang_ca_kin",
    "cat": "kinetics",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Ca-biochar (kinetics)",
      "note": "Twelve time points over 72 h that reach a clean plateau. The authors report PFO k1 = 6.26 and PSO k2 = 0.664 mg/g."
    },
    "ko": {
      "name": "Ca-바이오차의 인산염 흡착 (속도)",
      "note": "72시간에 걸친 12개 시간점이 뚜렷한 평탄역에 도달합니다. 논문은 PFO k₁ = 6.26, PSO k₂ = 0.664 mg/g를 보고했습니다."
    },
    "data": "t (h)\tqt (mg/g)\tsd\n0.5\t6.83\t0.29\n1\t7.1\t0.08\n1.5\t7.23\t0.15\n2\t7.75\t0.12\n3\t8.84\t0.21\n4\t9.31\t0.04\n6\t9.56\t0.04\n8\t9.62\t0.06\n12\t9.76\t0.05\n24\t9.79\t0.06\n48\t9.82\t0.01\n72\t9.83\t0.01",
    "ctx": {
      "T": "298.15",
      "C0": "20",
      "dose": "2",
      "radius": "0.05"
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  },
  {
    "id": "wang_al_kin",
    "cat": "kinetics",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Al-biochar (never equilibrates)",
      "note": "Uptake is still climbing at 72 h, which the paper states in its own text. Any q_e fitted to this is an extrapolation, and the rate constant goes with it."
    },
    "ko": {
      "name": "Al-바이오차의 인산염 흡착 (평형 미도달)",
      "note": "72시간에도 흡착량이 계속 증가하며, 논문 본문도 이를 밝히고 있습니다. 여기에 적합한 q_e는 외삽이며 속도상수도 함께 불확실해집니다."
    },
    "data": "t (h)\tqt (mg/g)\tsd\n0.5\t1.81\t0.3\n1\t2.34\t0.43\n1.5\t2.52\t0.36\n2\t2.86\t0.22\n3\t2.88\t0.14\n4\t3.45\t0.15\n6\t3.78\t0.2\n8\t4.05\t0.24\n12\t5.23\t0.47\n24\t6.55\t0.37\n48\t8.34\t0.48\n72\t9.25\t0.01",
    "ctx": {
      "T": "298.15",
      "C0": "20",
      "dose": "2",
      "radius": "0.05"
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  },
  {
    "id": "wang_mg_kin",
    "cat": "kinetics",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on Mg-biochar (two-stage uptake)",
      "note": "A fast surface stage followed by a slower one, which is what the Weber-Morris multi-region analysis and the double exponential model exist for."
    },
    "ko": {
      "name": "Mg-바이오차의 인산염 흡착 (2단계 흡착)",
      "note": "빠른 표면 단계에 이어 느린 단계가 나타납니다. Weber–Morris 다구간 해석과 이중지수 모델이 바로 이런 경우를 위한 것입니다."
    },
    "data": "t (h)\tqt (mg/g)\tsd\n0.5\t1.51\t0.02\n1\t1.98\t0.04\n1.5\t2.63\t0.03\n2\t7.38\t0.01\n3\t8.53\t0.03\n4\t8.93\t0.04\n6\t9.28\t0\n8\t9.54\t0.03\n12\t9.56\t0.02\n24\t9.86\t0.02\n48\t9.73\t0.01\n72\t9.82\t0.01",
    "ctx": {
      "T": "298.15",
      "C0": "20",
      "dose": "2",
      "radius": "0.05"
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  },
  {
    "id": "wang_la_kin",
    "cat": "kinetics",
    "cite": "Wang, P. et al. (2021) R. Soc. Open Sci. 8, 201789. Data: Zenodo 10.5281/zenodo.4711711 (CC0).",
    "en": {
      "name": "Phosphate on La-biochar (equilibrium before the first point)",
      "note": "Adsorption was essentially complete within the first half hour, so nothing in the data constrains the rate constant however tight its confidence interval looks."
    },
    "ko": {
      "name": "La-바이오차의 인산염 흡착 (첫 측정 이전에 평형 도달)",
      "note": "첫 30분 안에 흡착이 사실상 끝나므로, 신뢰구간이 아무리 좁아 보여도 데이터가 속도상수를 제약하지 못합니다."
    },
    "data": "t (h)\tqt (mg/g)\tsd\n0.5\t9.82\t0.04\n1\t9.87\t0.02\n1.5\t9.88\t0.03\n2\t9.87\t0.02\n3\t9.87\t0.02\n4\t9.88\t0.02\n6\t9.91\t0.01\n8\t9.89\t0.02\n12\t9.88\t0.04\n24\t9.91\t0.01\n48\t9.9\t0.01\n72\t9.91\t0.02",
    "ctx": {
      "T": "298.15",
      "C0": "20",
      "dose": "2",
      "radius": "0.05"
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  },
  {
    "id": "zhang_as_bc_iso",
    "cat": "isotherm",
    "cite": "Zhang, W. et al. (2018) R. Soc. Open Sci. 5, 181266. Raw data: Dryad 10.5061/dryad.kv63501 (CC0).",
    "en": {
      "name": "Arsenic on yak dung biochar (isotherm)",
      "note": "Arsenic(V) on plain biochar at 10 g/L. The uptake is small and the isotherm never turns over, so the fitted capacity sits well beyond the measured range."
    },
    "ko": {
      "name": "야크 분변 바이오차의 비소 흡착 (등온)",
      "note": "10 g/L 조건에서 무처리 바이오차에 흡착된 비소(V)입니다. 흡착량이 적고 등온선이 꺾이지 않으므로, 적합된 흡착용량은 측정 범위를 크게 벗어납니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tC0 (mg/L)\n3.97\t0.103\t5\n8.339\t0.1661\t10\n12.8\t0.22\t15\n17.26\t0.274\t20\n26.01\t0.399\t30\n35.12\t0.488\t40",
    "ctx": {
      "T": "298.15",
      "MW": "74.92",
      "Cs": "",
      "dose": "10"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "zhang_as_febc_iso",
    "cat": "isotherm",
    "cite": "Zhang, W. et al. (2018) R. Soc. Open Sci. 5, 181266. Raw data: Dryad 10.5061/dryad.kv63501 (CC0).",
    "en": {
      "name": "Arsenic on iron-modified biochar (isotherm)",
      "note": "The same biochar after FeCl2 treatment removes 99% of the arsenic. The isotherm rises steeply and then bends over, which is what a genuine affinity looks like."
    },
    "ko": {
      "name": "철 개질 바이오차의 비소 흡착 (등온)",
      "note": "FeCl₂로 개질한 같은 바이오차가 비소의 99%를 제거합니다. 등온선이 가파르게 올라간 뒤 꺾이며, 이는 실제로 친화도가 높을 때 나타나는 형태입니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tC0 (mg/L)\n0.0749\t0.4925\t5\n0.5158\t0.9484\t10\n1.837\t1.3163\t15\n1.926\t1.8074\t20\n3.328\t2.6672\t30\n12.91\t2.709\t40",
    "ctx": {
      "T": "298.15",
      "MW": "74.92",
      "Cs": "",
      "dose": "10"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "zhang_f_bc_iso",
    "cat": "isotherm",
    "cite": "Zhang, W. et al. (2018) R. Soc. Open Sci. 5, 181266. Raw data: Dryad 10.5061/dryad.kv63501 (CC0).",
    "en": {
      "name": "Fluoride on yak dung biochar (isotherm)",
      "note": "A well-shaped fluoride isotherm. Our non-linear Langmuir gives 4.98 mg/g against the 4.851 the paper reports, and R2 = 0.997."
    },
    "ko": {
      "name": "야크 분변 바이오차의 불소 흡착 (등온)",
      "note": "형태가 좋은 불소 등온선입니다. 비선형 Langmuir 적합은 4.98 mg/g로, 논문의 4.851과 가깝고 R²은 0.997입니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tC0 (mg/L)\n0.35\t0.465\t5\n0.84\t0.916\t10\n1.29\t1.371\t15\n2.08\t1.792\t20\n4.24\t2.576\t30\n6.88\t3.312\t40",
    "ctx": {
      "T": "298.15",
      "MW": "19.00",
      "Cs": "",
      "dose": "10"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "zhang_f_febc_iso",
    "cat": "isotherm",
    "cite": "Zhang, W. et al. (2018) R. Soc. Open Sci. 5, 181266. Raw data: Dryad 10.5061/dryad.kv63501 (CC0).",
    "en": {
      "name": "Fluoride on iron-modified biochar (isotherm)",
      "note": "Iron modification raises the affinity but lowers the capacity, so the two curves cross. Fitting both and comparing is the point of this pair."
    },
    "ko": {
      "name": "철 개질 바이오차의 불소 흡착 (등온)",
      "note": "철 개질은 친화도를 높이지만 흡착용량은 낮추므로 두 곡선이 교차합니다. 두 데이터를 함께 적합해 비교하는 것이 이 쌍의 목적입니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tC0 (mg/L)\n0.18\t0.482\t5\n0.46\t0.954\t10\n0.83\t1.417\t15\n1.48\t1.852\t20\n3.67\t2.633\t30\n6.94\t3.306\t40",
    "ctx": {
      "T": "298.15",
      "MW": "19.00",
      "Cs": "",
      "dose": "10"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "zhang_as_bc_kin",
    "cat": "kinetics",
    "cite": "Zhang, W. et al. (2018) R. Soc. Open Sci. 5, 181266. Raw data: Dryad 10.5061/dryad.kv63501 (CC0).",
    "en": {
      "name": "Arsenic on yak dung biochar (kinetics)",
      "note": "Nineteen points over 12 h, but the whole signal is 0.07 mg/g and the scatter is a large fraction of it. A good test of whether a rate constant means anything."
    },
    "ko": {
      "name": "야크 분변 바이오차의 비소 흡착 (속도)",
      "note": "12시간에 걸친 19개 점이지만 전체 신호가 0.07 mg/g에 불과하고 산포가 그중 상당 부분을 차지합니다. 속도상수에 의미가 있는지 시험해 보기 좋은 사례입니다."
    },
    "data": "t (min)\tqt (mg/g)\n5\t0.0159\n10\t0.0159\n15\t0.0232\n20\t0.0257\n30\t0.0266\n40\t0.0353\n50\t0.0394\n60\t0.0373\n120\t0.043\n180\t0.0435\n240\t0.051\n300\t0.0529\n360\t0.0601\n420\t0.0522\n480\t0.0542\n540\t0.0621\n600\t0.0642\n660\t0.0636\n720\t0.0742",
    "ctx": {
      "T": "298.15",
      "C0": "3.668",
      "dose": "10",
      "radius": ""
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  },
  {
    "id": "zhang_as_febc_kin",
    "cat": "kinetics",
    "cite": "Zhang, W. et al. (2018) R. Soc. Open Sci. 5, 181266. Raw data: Dryad 10.5061/dryad.kv63501 (CC0).",
    "en": {
      "name": "Arsenic on iron-modified biochar (kinetics)",
      "note": "Removal is 95% complete at the first measurement. The paper tabulates a pseudo-second-order q_e of 1.069 mg/g, but its own deposited data never exceed 0.364, which is what the fit here returns."
    },
    "ko": {
      "name": "철 개질 바이오차의 비소 흡착 (속도)",
      "note": "첫 측정 시점에 이미 95%가 제거되었습니다. 논문은 유사 2차 q_e를 1.069 mg/g로 표에 실었지만, 함께 공개된 원자료는 0.364를 넘지 않으며 여기서의 적합 결과도 그 값입니다."
    },
    "data": "t (min)\tqt (mg/g)\n5\t0.3477\n10\t0.3557\n15\t0.3571\n20\t0.3573\n30\t0.3604\n40\t0.3606\n50\t0.3589\n60\t0.3622\n120\t0.3627\n180\t0.3629\n240\t0.363\n300\t0.3633\n360\t0.3634\n420\t0.3636\n480\t0.3638\n540\t0.3639\n600\t0.3645\n660\t0.3648\n720\t0.3642",
    "ctx": {
      "T": "298.15",
      "C0": "3.668",
      "dose": "10",
      "radius": ""
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  },
  {
    "id": "zhang_f_bc_kin",
    "cat": "kinetics",
    "cite": "Zhang, W. et al. (2018) R. Soc. Open Sci. 5, 181266. Raw data: Dryad 10.5061/dryad.kv63501 (CC0).",
    "en": {
      "name": "Fluoride on yak dung biochar (kinetics)",
      "note": "A clean approach to equilibrium over 12 h. Pseudo-second-order gives 1.725 mg/g against the paper's 1.737."
    },
    "ko": {
      "name": "야크 분변 바이오차의 불소 흡착 (속도)",
      "note": "12시간에 걸쳐 평형에 깔끔하게 접근합니다. 유사 2차식은 1.725 mg/g를 주며, 논문 값 1.737과 일치합니다."
    },
    "data": "t (min)\tqt (mg/g)\n5\t1.504\n10\t1.565\n15\t1.616\n20\t1.656\n30\t1.68\n40\t1.685\n50\t1.693\n60\t1.69\n120\t1.71\n180\t1.716\n240\t1.722\n300\t1.72\n360\t1.725\n420\t1.723\n480\t1.727\n540\t1.728\n600\t1.732\n660\t1.732\n720\t1.732",
    "ctx": {
      "T": "298.15",
      "C0": "19.0",
      "dose": "10",
      "radius": ""
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  },
  {
    "id": "zhang_f_febc_kin",
    "cat": "kinetics",
    "cite": "Zhang, W. et al. (2018) R. Soc. Open Sci. 5, 181266. Raw data: Dryad 10.5061/dryad.kv63501 (CC0).",
    "en": {
      "name": "Fluoride on iron-modified biochar (kinetics)",
      "note": "Faster than the unmodified biochar and flat after about an hour, so both q_e and the rate constant are well determined here."
    },
    "ko": {
      "name": "철 개질 바이오차의 불소 흡착 (속도)",
      "note": "무처리 바이오차보다 빠르며 약 1시간 뒤부터 평탄해집니다. 따라서 q_e와 속도상수 모두 잘 결정됩니다."
    },
    "data": "t (min)\tqt (mg/g)\n5\t1.557\n10\t1.62\n15\t1.694\n20\t1.723\n30\t1.752\n40\t1.772\n50\t1.778\n60\t1.78\n120\t1.78\n180\t1.782\n240\t1.778\n300\t1.782\n360\t1.783\n420\t1.78\n480\t1.786\n540\t1.781\n600\t1.788\n660\t1.788\n720\t1.782",
    "ctx": {
      "T": "298.15",
      "C0": "19.0",
      "dose": "10",
      "radius": ""
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  },
  {
    "id": "tao_levo_iso_20",
    "cat": "isotherm",
    "cite": "Tao, J. et al. (2020) R. Soc. Open Sci. 7, 200857. Raw data: Dryad 10.5061/dryad.47d7wm39s (CC0).",
    "en": {
      "name": "Levofloxacin on cellulose nanocrystal / graphene oxide, 20 C",
      "note": "An antibiotic on a composite adsorbent. Sips returns 17.29 mg/g, the same figure the paper reports, while Langmuir returns 49.7 mg/g from data that never approach saturation."
    },
    "ko": {
      "name": "셀룰로스 나노결정/산화graphene 복합체의 레보플록사신 흡착, 20 °C",
      "note": "복합 흡착제에 대한 항생제 흡착입니다. Sips는 논문과 같은 17.29 mg/g를 주지만, Langmuir는 포화에 전혀 접근하지 않은 데이터로부터 49.7 mg/g를 내놓습니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\n2.7066\t1.2934\n3.6314\t5.3686\n4.982\t9.018\n6.754\t11.246\n9.0965\t13.1035\n11.988\t15.012\n14.8644\t17.1356",
    "ctx": {
      "T": "293.15",
      "MW": "397.83",
      "Cs": "",
      "dose": ""
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "tao_levo_iso_30",
    "cat": "isotherm",
    "cite": "Tao, J. et al. (2020) R. Soc. Open Sci. 7, 200857. Raw data: Dryad 10.5061/dryad.47d7wm39s (CC0).",
    "en": {
      "name": "Levofloxacin on cellulose nanocrystal / graphene oxide, 30 C",
      "note": "The middle of the three temperatures. Uptake rises with temperature here, which is the signature of an endothermic process."
    },
    "ko": {
      "name": "셀룰로스 나노결정/산화graphene 복합체의 레보플록사신 흡착, 30 °C",
      "note": "세 온도 가운데 중간입니다. 온도가 오를수록 흡착량이 증가하며, 이는 흡열 과정의 특징입니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\n2.5066\t2.5456\n3.4314\t6.6188\n4.782\t11.2682\n6.554\t13.4962\n8.8965\t15.6537\n11.7888\t17.2622\n14.6644\t19.3858",
    "ctx": {
      "T": "303.15",
      "MW": "397.83",
      "Cs": "",
      "dose": ""
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "tao_levo_iso_40",
    "cat": "isotherm",
    "cite": "Tao, J. et al. (2020) R. Soc. Open Sci. 7, 200857. Raw data: Dryad 10.5061/dryad.47d7wm39s (CC0).",
    "en": {
      "name": "Levofloxacin on cellulose nanocrystal / graphene oxide, 40 C",
      "note": "The warmest of the three isotherms, and the highest capacity. Load all three into the thermodynamics tab to get the van 't Hoff parameters."
    },
    "ko": {
      "name": "셀룰로스 나노결정/산화graphene 복합체의 레보플록사신 흡착, 40 °C",
      "note": "세 등온선 가운데 가장 높은 온도이며 흡착용량도 가장 큽니다. 세 데이터를 열역학 탭에 함께 넣으면 van 't Hoff 매개변수를 얻을 수 있습니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\n2.9066\t3.3292\n3.8314\t8.1044\n5.182\t12.7588\n6.954\t15.9818\n9.2965\t18.6392\n12.188\t20.7478\n15.0644\t22.8714",
    "ctx": {
      "T": "313.15",
      "MW": "397.83",
      "Cs": "",
      "dose": ""
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "tao_levo_kin",
    "cat": "kinetics",
    "cite": "Tao, J. et al. (2020) R. Soc. Open Sci. 7, 200857. Raw data: Dryad 10.5061/dryad.47d7wm39s (CC0).",
    "en": {
      "name": "Levofloxacin on cellulose nanocrystal / graphene oxide (kinetics)",
      "note": "Fifteen points from 3 min to 18 h, spanning nearly three decades of time. The long tail is what makes the difference between the kinetic models visible."
    },
    "ko": {
      "name": "셀룰로스 나노결정/산화graphene 복합체의 레보플록사신 흡착 (속도)",
      "note": "3분부터 18시간까지 15개 점으로, 시간 축을 거의 세 자릿수에 걸쳐 덮습니다. 긴 꼬리 덕분에 속도식 사이의 차이가 드러납니다."
    },
    "data": "t (min)\tqt (mg/g)\n3\t0.686\n5\t0.998\n10\t1.238\n20\t1.445\n40\t3.786\n60\t5.593\n90\t6.086\n120\t6.591\n150\t7.223\n180\t7.675\n240\t8.075\n360\t8.394\n540\t8.772\n720\t8.901\n1080\t9.195",
    "ctx": {
      "T": "293.15",
      "C0": "",
      "dose": "",
      "radius": ""
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  },
  {
    "id": "xue_cd_iso",
    "cat": "isotherm",
    "cite": "Xue, Z. et al. (2019) R. Soc. Open Sci. 6, 182195. Raw data: Dryad 10.5061/dryad.sg2637q (CC0).",
    "en": {
      "name": "Cadmium on a mesoporous ceramic nanomaterial",
      "note": "Worth fitting carefully. The paper reports a Langmuir capacity of 97.09 mg/g with R2 = 0.9832, but those come from the linearised Ce/qe plot. Fitting the same points directly gives 72.3 mg/g with R2 = 0.65, and the linear plots tab shows why the two disagree."
    },
    "ko": {
      "name": "메조다공성 세라믹 나노소재의 카드뮴 흡착",
      "note": "주의해서 적합해 볼 가치가 있습니다. 논문은 Langmuir 흡착용량 97.09 mg/g와 R² = 0.9832를 보고하지만, 이는 Ce/qe 선형 그래프에서 얻은 값입니다. 같은 점들을 직접 적합하면 72.3 mg/g, R² = 0.65가 나오며, 선형 그래프 탭에서 그 차이의 이유를 볼 수 있습니다."
    },
    "data": "Ce (mg/L)\tqe (mg/g)\tsd\tC0 (mg/L)\n1.67\t12.04\t0.18\t50\n1.094\t24.67\t0.04\t100\n1.297\t37.08\t0.06\t150\n33.863\t53.83\t0.86\t250\n73.667\t56.4\t1.29\t300\n155.85\t60.84\t0.78\t400\n225.133\t68.58\t3.64\t500\n572.467\t106.55\t16.11\t1000",
    "ctx": {
      "T": "298.15",
      "MW": "112.41",
      "Cs": "",
      "dose": "4"
    },
    "models": [
      "langmuir",
      "freundlich",
      "sips",
      "toth",
      "redlich_peterson"
    ]
  },
  {
    "id": "xue_cd_kin",
    "cat": "kinetics",
    "cite": "Xue, Z. et al. (2019) R. Soc. Open Sci. 6, 182195. Raw data: Dryad 10.5061/dryad.sg2637q (CC0).",
    "en": {
      "name": "Cadmium on a mesoporous ceramic nanomaterial (kinetics)",
      "note": "Eight points with replicate error bars, flat from 150 min onward, so q_e is measured rather than fitted. Pseudo-first-order fails here while pseudo-second-order and Avrami both describe it."
    },
    "ko": {
      "name": "메조다공성 세라믹 나노소재의 카드뮴 흡착 (속도)",
      "note": "반복 측정 오차막대를 포함한 8개 점이며 150분 이후 평탄하므로 q_e는 적합이 아니라 측정된 값입니다. 유사 1차식은 맞지 않고 유사 2차식과 Avrami가 잘 설명합니다."
    },
    "data": "t (min)\tqt (mg/g)\tsd\n30\t44.29\t0.27\n60\t46.12\t0.83\n90\t46.74\t1.54\n120\t47.49\t0.25\n150\t48.54\t0.56\n180\t48.53\t0.09\n240\t48.52\t0.16\n300\t48.51\t0.06",
    "ctx": {
      "T": "298.15",
      "C0": "200.0",
      "dose": "4",
      "radius": ""
    },
    "models": [
      "pfo",
      "pso",
      "elovich",
      "avrami"
    ]
  }
];

/* Thermodynamics needs a set of isotherms at different
   temperatures rather than a single series. */
const THERMO_PRESETS = [
  {
    "id": "tao_levo_thermo",
    "cat": "thermo",
    "cite": "Tao, J. et al. (2020) R. Soc. Open Sci. 7, 200857. Raw data: Dryad 10.5061/dryad.47d7wm39s (CC0).",
    "en": {
      "name": "Levofloxacin on cellulose nanocrystal / graphene oxide",
      "note": "Isotherms at 293.15, 303.15 and 313.15 K from one paper, which is the minimum a van 't Hoff analysis needs. The capacity rises with temperature and the enthalpy comes out endothermic at about +34 kJ/mol, but with three points the line is only moderately determined, and the Langmuir route gives a different answer from the distribution coefficient used here. That disagreement is the reason the route has to be stated in any paper quoting these numbers."
    },
    "ko": {
      "name": "셀룰로스 나노결정/산화graphene 복합체의 레보플록사신 흡착",
      "note": "한 논문에서 293.15, 303.15, 313.15 K에 측정한 등온선으로, van 't Hoff 해석에 필요한 최소 구성입니다. 온도가 오를수록 흡착용량이 커지고 엔탈피는 약 +34 kJ/mol의 흡열로 나옵니다. 다만 점이 세 개뿐이라 직선이 제한적으로만 결정되며, Langmuir 경로는 여기서 사용한 분배계수 경로와 다른 값을 줍니다. 이 불일치야말로 이 값을 인용하는 논문이 변환 경로를 반드시 밝혀야 하는 이유입니다."
    },
    "MW": "397.83",
    "model": "sips",
    "route": "kd_density",
    "datasets": [
      [
        "293.15",
        "2.7066\t1.2934\n3.6314\t5.3686\n4.982\t9.018\n6.754\t11.246\n9.0965\t13.1035\n11.988\t15.012\n14.8644\t17.1356"
      ],
      [
        "303.15",
        "2.5066\t2.5456\n3.4314\t6.6188\n4.782\t11.2682\n6.554\t13.4962\n8.8965\t15.6537\n11.7888\t17.2622\n14.6644\t19.3858"
      ],
      [
        "313.15",
        "2.9066\t3.3292\n3.8314\t8.1044\n5.182\t12.7588\n6.954\t15.9818\n9.2965\t18.6392\n12.188\t20.7478\n15.0644\t22.8714"
      ]
    ]
  }
];
