# -*- coding: utf-8 -*-
"""Generate the parts of the site that exist so a search engine can read it.

A crawler never runs Pyodide, so everything the app knows about its models
lives out of reach behind a 30 MB WebAssembly download. Without help, the
only text Google can see is the panel furniture: roughly five hundred words
of "Data", "Experiment", "Fit models". Nobody looking for a Redlich-Peterson
fit would ever find this page.

So the model catalogue is written into index.html as ordinary markup. It is
generated from the same ModelSpec objects the fitter uses, which means it
cannot drift: add a model in py/isotherms.py, run this, and it appears.

Also writes sitemap.xml and robots.txt.

Run:  python tools/make_seo.py
      python tools/make_seo.py --check   exit non-zero if index.html is stale
"""
import os
import re
import sys

sys.path.insert(0, "py")

SITE = "https://nguyenducanh97.github.io/adsorpfit/"

START = "<!-- SEO:MODELS start, generated by tools/make_seo.py -->"
END = "<!-- SEO:MODELS end -->"

SUB_DIGITS = dict(zip("₀₁₂₃₄₅₆₇₈₉₊₋ₐₑₕᵢⱼₖₗₘₙₒₚᵣₛₜᵤᵥₓ",
                      "0123456789+-aehijklmnoprstuvx"))
SUP_CHARS = dict(zip("⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻ᵅ", "0123456789+-a"))

# longest first, so varepsilon is not matched as epsilon with a stray "var"
GREEK = [("varepsilon", "ε"), ("epsilon", "ε"), ("lambda", "λ"),
         ("Delta", "Δ"), ("alpha", "α"), ("gamma", "γ"), ("delta", "δ"),
         ("sigma", "σ"), ("theta", "θ"), ("omega", "ω"), ("beta", "β"),
         ("circ", "°"), ("chi", "χ"), ("phi", "φ"), ("tau", "τ"),
         ("mu", "μ"), ("nu", "ν")]


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def sci(s):
    """The Python twin of sci() in js/app.js, applied at build time.

    The same passes in the same order: Unicode runs first so a later ASCII
    rule cannot split them, then braced forms, then bare ones.
    """
    def sub_run(m):
        return ("<sub>" + "".join(SUB_DIGITS.get(c, c) for c in m.group(0))
                + "</sub>")

    def sup_run(m):
        run = m.group(0)
        if not re.search(r"[⁰¹²³⁴⁵⁶⁷⁸⁹⁻ᵅ]", run):
            return run                      # a lone middle dot is punctuation
        return ("<sup>" + "".join(SUP_CHARS.get(c, c) for c in run)
                + "</sup>")

    s = re.sub(r"[₀-₉ₐₑₕᵢⱼₖₗₘₙₒₚᵣₛₜᵤᵥₓ]+", sub_run, s)
    s = re.sub(r"[⁰¹²³⁴-⁹⁺⁻ᵅ·]+", sup_run, s)
    s = re.sub(r"([A-Za-z])_\{([^}]{1,10})\}", r"\1<sub>\2</sub>", s)
    s = re.sub(r"\^\{([^}]{1,10})\}", r"<sup>\1</sup>", s)
    s = re.sub(r"([A-Za-z])_([A-Za-z0-9]{1,6})(?![A-Za-z0-9_])",
               r"\1<sub>\2</sub>", s)
    s = re.sub(r"\^(−?-?[0-9A-Za-z.]{1,4})", r"<sup>\1</sup>", s)
    return s


def tex_to_html(t):
    """Render a parameter symbol from its LaTeX form.

    Every symbol carries a hand-written LaTeX form because that is what
    KaTeX draws in the app, so converting from it keeps this catalogue and
    the live tables saying the same thing. Pattern-matching the plain
    symbol instead would split q_{e,cal} after the comma.
    """
    t = re.sub(r"\\mathrm\{([^}]*)\}", r"\1", t)
    t = re.sub(r"\\text\{([^}]*)\}", r"\1", t)
    for name, ch in GREEK:
        t = t.replace("\\" + name, ch)
    t = re.sub(r"_\{([^}]*)\}", r"<sub>\1</sub>", t)
    t = re.sub(r"\^\{([^}]*)\}", r"<sup>\1</sup>", t)
    t = re.sub(r"_([A-Za-z0-9])", r"<sub>\1</sub>", t)
    t = re.sub(r"\^([A-Za-z0-9])", r"<sup>\1</sup>", t)
    return t.replace("\\,", " ").replace("$", "")


def entries(models):
    """One definition-list row per model: name, year, what it assumes, source."""
    rows = []
    for key, m in models.items():
        why = m.assumptions[0] if m.assumptions else ""
        year = (' <span class="mi-year">%s</span>' % m.year) if m.year else ""
        params = ", ".join(tex_to_html(esc(p.symbol_tex)) for p in m.params)
        rows.append(
            '          <dt id="model-%s">%s%s</dt>\n'
            '          <dd>%s <span class="mi-p">Fitted parameters: %s.</span>'
            ' <cite>%s</cite></dd>'
            % (key.replace("_", "-"), sci(esc(m.name)), year,
               sci(esc(why)), params, esc(m.citation or "")))
    return "\n".join(rows)


def block():
    from isotherms import ISOTHERM_MODELS
    from kinetics import KINETIC_MODELS
    ni, nk = len(ISOTHERM_MODELS), len(KINETIC_MODELS)
    return """%s
    <div class="panel mi-panel" id="model-index">
      <div class="panel-head"><h2>Every model AdsorpFit can fit</h2></div>
      <div class="panel-body">
        <p>AdsorpFit fits %d adsorption isotherm models and %d adsorption kinetic
        models to your own measurements, then runs a full van 't Hoff
        thermodynamic analysis, entirely inside your browser. Fitting is by
        bounded non-linear least squares, with linearised forms offered
        alongside for comparison. Every fit returns parameter standard errors,
        95%% confidence intervals, AICc ranking against the other models you
        selected, checks that the data actually fall inside the model's valid
        domain, and a written interpretation of what the numbers mean. Nothing
        you paste is uploaded anywhere.</p>

        <h3>Adsorption isotherm models (%d)</h3>
        <dl class="model-index">
%s
        </dl>

        <h3>Adsorption kinetic models (%d)</h3>
        <dl class="model-index">
%s
        </dl>

        <h3>Adsorption thermodynamics</h3>
        <p>From isotherms measured at three or more temperatures, AdsorpFit
        derives the standard Gibbs free energy change, the standard enthalpy
        change and the standard entropy change by the van 't Hoff method, using
        a genuinely dimensionless equilibrium constant. Six documented routes to
        that dimensionless constant are offered, because a van 't Hoff plot
        built on a constant that still carries units is the single most common
        error in the adsorption literature. Isosteric heat of adsorption as a
        function of surface loading, Arrhenius activation energy from fitted
        rate constants, and sticking probability are also available.</p>
      </div>
    </div>
%s""" % (START, ni, nk, ni, entries(ISOTHERM_MODELS),
         nk, entries(KINETIC_MODELS), END)


def splice(html, new):
    if START in html and END in html:
        a = html.index(START)
        b = html.index(END) + len(END)
        return html[:a] + new + html[b:]
    anchor = "  </section>\n</main>"
    assert anchor in html, "could not find the end of the guide section"
    return html.replace(anchor, new + "\n" + anchor, 1)


def sitemap():
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            '  <url>\n'
            '    <loc>%s</loc>\n'
            '    <changefreq>monthly</changefreq>\n'
            '    <priority>1.0</priority>\n'
            '  </url>\n'
            '</urlset>\n' % SITE)


def robots():
    return "User-agent: *\nAllow: /\n\nSitemap: %ssitemap.xml\n" % SITE


if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    html = open("index.html", encoding="utf-8").read()
    out = splice(html, block())
    stale = out != html
    if "--check" in sys.argv:
        print("index.html is %s" % ("STALE, run tools/make_seo.py" if stale
                                    else "up to date with the model specs"))
        sys.exit(1 if stale else 0)
    if stale:
        open("index.html", "w", encoding="utf-8", newline="").write(out)
    open("sitemap.xml", "w", encoding="utf-8", newline="").write(sitemap())
    open("robots.txt", "w", encoding="utf-8", newline="").write(robots())
    print("index.html %s" % ("updated" if stale else "unchanged"))
    print("sitemap.xml and robots.txt written")
